foreach(scenario homing homing-reference homing-departure homing-timeout homing-estop)
    foreach(run RANGE 1 2)
        execute_process(COMMAND "${RUNNER}" --quiet --scenario ${scenario}
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Homing replay ${scenario} failed: ${output} ${error}")
        endif()
        if(run EQUAL 1)
            set(first "${output}")
        elseif(NOT first STREQUAL output)
            message(FATAL_ERROR "Homing replay differs: ${scenario}\n${first}\n${output}")
        endif()
    endforeach()
endforeach()
message(STATUS "Homing/reference/departure/timeout/ESTOP results replay identically")
