foreach(directory app tasks rtos protocol health drivers control safety)
    file(GLOB_RECURSE sources "${SOURCE_ROOT}/firmware/${directory}/*.c" "${SOURCE_ROOT}/firmware/${directory}/*.h")
    foreach(source IN LISTS sources)
        file(READ "${source}" content)
        string(TOLOWER "${content}" lower_content)
        string(REPLACE "\\" "/" lower_content "${lower_content}")
        if(lower_content MATCHES "#[ \t]*include[ \t]*[<\"][^\n]*(platform/host|windows[.]h|winbase[.]h|processthreadsapi[.]h|synchapi[.]h|simulator/)")
            message(FATAL_ERROR "Host-specific include in portable firmware: ${source}")
        endif()
        if(content MATCHES "(^|[^a-zA-Z0-9_])(Sleep|CreateThread|CreateEvent[A-W]*|WaitForSingleObject|WaitForMultipleObjects|EnterCriticalSection|LeaveCriticalSection|QueryPerformanceCounter|QueryPerformanceFrequency|GetTickCount[0-9]*)[ \t]*\\(")
            message(FATAL_ERROR "Windows API call in portable firmware: ${source}")
        endif()
        if(content MATCHES "#[ \t]*include[ \t]*[<\"][^\n]*(platform/host|_host[.]h|windows[.]h|pthread[.]h|simulator/|control_metrics[.]h|plant_[a-zA-Z0-9_]*[.]h)")
            message(FATAL_ERROR "Host-specific include in portable firmware: ${source}")
        endif()
        if(content MATCHES "(host_[a-zA-Z0-9_]+|[a-zA-Z0-9_]+_host_[a-zA-Z0-9_]+|plant_[a-zA-Z0-9_]+)[ \t]*\\(")
            message(FATAL_ERROR "Host-control call in portable firmware: ${source}")
        endif()
    endforeach()
endforeach()
message(STATUS "Portable application/tasks/RTOS/protocol/health/driver files have no host includes or control calls")
